spring:
  application:
    name: core
  autoconfigure:
    exclude: org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: itechwx
    password: ItechwxPass123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
itechwx:
  security:
    registration-rate-limit:
      maximum-attempts: 5
      window: PT1M
server:
  port: 8081
